spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      format_sql: false
api:
  endpoint:
    base-url: /api/v1